version: '3.8'

services:
  app:
    image: skyfay/docker-to-notion:latest
    container_name: docker-to-notion
    hostname: your-hostname # Not needed if you use linux and /etc/hostname
    environment:
      - NOTION_API_KEY=your_notion_api_key
      - NOTION_DATABASE_ID=your_database_id
      - EXCLUDED_IMAGES=["skyfay/docker-to-notion"] # [] = exclude no images, ["image", "image2"] = exclude multiple images
      - SYNC_INTERVAL=3600  # the lowest value is 300 / 5 minutes

      # If you have images github container registry (ghcr)
      - GITHUB_TOKEN=your_github_token # https://github.com/settings/tokens only need read:packages permission

      # If you have images with aws container registry (ecr)
      - AWS_ACCESS_KEY=your_aws_access_key
      - AWS_SECRET_KEY=your_aws_secret_key
      - AWS_REGION='eu-central-1'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/hostname:/etc/hostname:ro # Linux only instead use docker hostname above
    restart: unless-stopped